// Lucide icons — tree-shakeable, consistent 24x24 stroke style
export {
  ArrowRight as ArrowRightIcon,
  ArrowUpDown as SortIcon,
  BadgeCheck as VerifiedIcon,
  BarChart3 as ChartBarIcon,
  Bell as BellIcon,
  Bold as FormatBoldIcon,
  CheckCircle as CheckCircleIcon,
  Clipboard as ClipboardIcon,
  Clock as ClockIcon,
  Code as FormatCodeIcon,
  Eye as EyeIcon,
  EyeOff as FormatSpoilerIcon,
  File as FileIcon,
  FileText as DocumentIcon,
  Frown as SadFaceIcon,
  Globe as GlobeIcon,
  Handshake as HandshakeIcon,
  Image as ImageIcon,
  Info as InfoIcon,
  Italic as FormatItalicIcon,
  Link as LinkIcon,
  Lock as LockIcon,
  Mailbox as MailboxIcon,
  Megaphone as MegaphoneIcon,
  Monitor as MonitorIcon,
  Newspaper as NewspaperIcon,
  Palette as PaletteIcon,
  Pencil as EditIcon,
  RefreshCcw as RefundIcon,
  Satellite as SatelliteIcon,
  ScrollText as ScrollIcon,
  Search as SearchIcon,
  SearchX as SearchOffIcon,
  Share2 as ShareIcon,
  SlidersHorizontal as FilterIcon,
  Strikethrough as FormatStrikethroughIcon,
  Underline as FormatUnderlineIcon,
  User as PersonIcon,
  Video as VideoIcon,
  Volume2 as SpeakerIcon,
  Wallet as WalletIcon,
  X as CrossIcon,
} from 'lucide-react';

// Domain-specific custom SVG icons (no lucide equivalent)
export { CoinIcon } from './coin-icon';
export {
  DefaultPostIcon,
  ForwardIcon,
  GiveawayIcon,
  IntegrationIcon,
  MentionIcon,
  NativePostIcon,
  PinnedIcon,
  PollIcon,
  PostTypeIcon,
  RepostIcon,
  ReviewIcon,
  StoryIcon,
} from './post-type-icons';
export { TelegramIcon } from './telegram-icon';
export { TonDiamondIcon } from './ton-diamond-icon';
export { VerifiedBadge } from './verified-badge';
