#!/usr/bin/env bash
set -euo pipefail

# Mini App API edge canary routing.
# Controls /api/** traffic split between stable_backend and canary_backend in nginx.
#
# Usage: ./api-canary-set.sh <percent>
# Examples:
#   ./api-canary-set.sh 0
#   ./api-canary-set.sh 1
#   ./api-canary-set.sh 10
#   ./api-canary-set.sh 100
#
# Sticky key:
# - Prefer header `X-Canary-Key` (recommended: Telegram user.id from Mini App)
# - Fallback to client IP (remote_addr)
#
# Forced override for testers:
# - Cookie `am_canary=1` -> always canary
# - Cookie `am_canary=0` -> always stable

PERCENT="${1:?Usage: $0 <percent>}"

if ! [[ "$PERCENT" =~ ^[0-9]{1,3}$ ]]; then
  echo "ERROR: percent must be an integer between 0 and 100, got: ${PERCENT}"
  exit 1
fi
if (( PERCENT < 0 || PERCENT > 100 )); then
  echo "ERROR: percent must be between 0 and 100, got: ${PERCENT}"
  exit 1
fi

DEPLOY_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="${DEPLOY_DIR}/nginx/canary-api-split.conf"

tmp="$(mktemp)"
{
  echo "# Generated by scripts/api-canary-set.sh (UTC: $(date -u +%Y-%m-%dT%H:%M:%SZ))"
  echo "split_clients \"\${api_canary_seed}\" \$api_canary_split {"
  if (( PERCENT <= 0 )); then
    echo "    * \"stable\";"
  elif (( PERCENT >= 100 )); then
    echo "    * \"canary\";"
  else
    echo "    ${PERCENT}% \"canary\";"
    echo "    * \"stable\";"
  fi
  echo "}"
} > "${tmp}"

mv "${tmp}" "${OUT_FILE}"

echo "==> Validating nginx config..."
docker exec am-nginx nginx -t

echo "==> Reloading nginx..."
docker exec am-nginx nginx -s reload

echo "==> Mini App API canary set to ${PERCENT}%"

